In [2]:
import numpy as np
import time

In [11]:
list0 = np.array([1,2,3,4,5,6])
print(arr,type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [8]:
SIZE = 1_000_000
py_list = list(range(SIZE))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"time required for python list {end - start}")
np_array = np.array(py_list)
start = time.time()
#vectorization
sq_array = np_array**2
end = time.time()
print(f"time required for nd array {end - start}")


time required for python list 0.12745094299316406
time required for nd array 0.005486011505126953


In [10]:
#memory
import sys
print(f"size of python list {sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"size of python list {np_array.nbytes} bytes")

size of python list 8000056000000 bytes
size of python list 8000000 bytes


In [ ]:
#Creation of arrays

In [19]:
#1.From lists
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)
print(arr1,type(arr1),arr1.dtype,arr1.shape)
list1.append("SHiva")
arr2 = np.array(list1)
print(arr2,type(arr2),arr2.dtype,arr2.shape)

##2D Arrays:-
arr2D = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(arr2D , arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' '6' 'SHiva'] <class 'numpy.ndarray'> <U21 (7,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [ ]:
#2. From built in functions

In [32]:
arr3 = np.zeros((2,3),dtype="int64" )
print(arr3,arr3.shape)

arr3 = np.ones((2,3),dtype="int64" )
print(arr3,arr3.shape)

arr3 = np.full((2,3),100,dtype="int64")
print(arr3,arr3.shape)
#identity matrix  --> diagonal ele = 1 and remaining is 0
arr4 = np.eye(4)
print(arr4,arr4.shape)
#Range function:
arr5 = np.arange(1,11,2)  #arange(start,end,step size)
print(arr5,arr5.shape)
#Evenly spaced 
arr5 = np.linspace(1,100,4) 
print(arr5,arr5.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [36]:
#Properties of numpy arrays 
#1.shape
print(arr1.shape)
#2.Size
print(arr1.size)
#3.dtype
print(arr1.dtype)
#4.ndim
print(arr1.ndim)

#type casting 
float_arr = arr1.astype(np.float64)
print(float_arr,arr1)

(6,)
6
int64
1
[1. 2. 3. 4. 5. 6.] [1 2 3 4 5 6]


In [41]:
#Operations 
#1.Reshaping
arr6 = np.array([[1,2,3],[4,5,6]])
print(arr6,arr6.shape)

reshape = arr6.reshape((3,2))
print(reshape,reshape.shape)

flatten = arr6.flatten()
print(flatten)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [42]:
#Indexing 
#Normal indexing : 
arr8 = np.array([1,2,3,4,5,6])
print(arr8[3])

#Fancy Indexing
idx = [1,2,3]
print(arr8[idx])

#Boolean Indexing
print(arr[arr>2])


4
[2 3 4]
[3 4 5 6]


In [43]:
#Scilicing 
print(arr8[1:4])
print(arr8[::2])

[2 3 4]
[1 3 5]


In [46]:
#sclicing in the list and nunpy
list1 = [1,2,3,4,6]
s1 = list1[2:4]
s1[0] = 100
print(list1)

array = np.array([1,2,3,4,6])
s2 = array[2:4]
s2[0]=200
print(array)

[1, 2, 3, 4, 6]
[  1   2 200   4   6]


In [52]:
#Multidimensional arrays
array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(array_2D))
sum_of_rows = np.sum(arr2D,axis=0)
print(sum_of_rows)
sum_of_cols = np.sum(arr2D,axis=1)
print(sum_of_cols)

print(arr2D[0:2,1:2])

45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [57]:
arr3D = np.array([[[1,2],[3,4]],
                  [[6,7],[8,9]],
                  [[10,11],[12,13]]
                 ]) #3*2*2
print(arr3D,arr3D.shape)
#indexing
print(arr3D[0,1,1])
#slicing
print(arr3D[:,0,:])

[[[ 1  2]
  [ 3  4]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]] (3, 2, 2)
4
[[ 1  2]
 [ 6  7]
 [10 11]]


In [3]:
#vetorization
arr9 = np.array([1,2,3,4,5])
arr10 = np.array([6,7,8,9,10])
print(arr9+arr10)

[ 7  9 11 13 15]


In [4]:
#Broadcasting
arr11 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr9+arr11)

[[ 2  4  6  8 10]
 [ 6  8 10 12 14]]


In [8]:
#Normalize
mean = np.mean(arr11)
std_dev = np.std(arr11)
normalized_arr = (arr11-mean)/std_dev

print(normalized_arr)
print(f"(mean,std) = ({np.mean(normalized_arr)},({np.std(normalized_arr)})")

[[-1.63299316 -1.22474487 -0.81649658 -0.40824829  0.        ]
 [ 0.          0.40824829  0.81649658  1.22474487  1.63299316]]
(mean,std) = (4.4408920985006264e-17,(1.0000000000000002)
